#!/usr/bin/env bash
# Bash script that displays listening ports
ss -tnlp | awk '
BEGIN {
  print "Active Internet connections (only servers)"
  print "Proto Recv-Q Send-Q Local Address      Foreign Address     State    PID/Program name"
}
{
  printf "%-5s %4s %4s %-20s %-20s %-10s %s/%s\n", $1, $2, $3, $4, $5, $6, $7, $8
}' | grep LISTEN
