#!/usr/bin/env bash
# Install nginx and configure to serve a simple web page
sudo apt-get -y install nginx
echo "<html><body><h1>Welcome to Nginx!</h1></body></html>" | sudo tee /var/www/html/index.html > /dev/null
sudo systemctl is-active --quiet nginx || sudo systemctl start nginx
