#!/usr/bin/env bash
# Install nginx and configure to serve a simple web page
apt-get update
apt-get -y install nginx
echo "<html><body><h1>Welcome to Nginx!</h1></body></html>" > /var/www/html/index.html
systemctl start nginx
