#!/usr/bin/env bash
# This script displays the content of the current directory in a list format,
# showing only the part of the name after the first dash.

#Using a for loop to iterate through the files in the current directory
for file in *; do
	# check if the file is not hidden and is a regular file
	if [ ! -f "$file" ] || [[ "$file" == .* ]]; then
		continue
	fi

	#extract the part of the name after the first dash
	name=$(echo "$file" | cut -d '-' -f2-)
	
	#display the formatted output
	echo "$name"
done
